CREATE TABLE "employees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nip" varchar,
  "name" varchar,
  "address" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "menus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "category" varchar,
  "description" varchar,
  "price" int,
  "image_url" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "menu_id" int,
  "quantity" int,
  "total" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "transactions" ADD FOREIGN KEY ("menu_id") REFERENCES "menus" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
